#!/usr/bin/env python3
"""Engine tests: builds a deck covering every slide type, then verifies with
python-pptx read-back that the file is valid and content is native/editable.

Run: python3 tests/test_engine.py   (from presentation/pptx/, or anywhere)
Exit 0 = all tests pass.
"""
import base64
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "scripts"))

from pptx import Presentation  # noqa: E402
from pptx_engine import build_deck, load_json  # noqa: E402

OUT_DIR = os.path.join(HERE, "output")

TINY_PNG = base64.b64decode(
    "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=="
)

SPEC = {
    "project": "SYNTHETIC TEST FIXTURE (not a real project)",
    "slides": [
        {"type": "title", "title": "Engine Self-Test Deck",
         "subtitle": "Synthetic fixture — exercises every slide type",
         "meta": ["presentation-Resources-And-Skills", "generated by test_engine.py"],
         "notes": "Notes on title slide."},
        {"type": "section", "phase": "PHASE 1 — FOUNDATION", "title": "Test Section",
         "notes": "Notes on section slide."},
        {"type": "bullets", "title": "Bullets Slide",
         "bullets": [{"text": "First verified point", "level": 0},
                     {"text": "Sub-point", "level": 1},
                     {"text": "Another point", "level": 0}],
         "badge": "IMPLEMENTED (verified)", "notes": "Notes on bullets slide."},
        {"type": "two_column", "title": "Two Column",
         "left_heading": "Left", "left_bullets": ["L1", "L2"],
         "right_heading": "Right", "right_bullets": ["R1", "R2"], "notes": "Notes on two-column."},
        {"type": "table", "title": "Tech Stack",
         "columns": ["Layer", "Technology"], "rows": [["Frontend", "React"], ["Backend", "FastAPI"]],
         "col_widths": [3.0, 6.0], "badge": "IMPLEMENTED (verified)", "notes": "Notes on table."},
        {"type": "diagram", "title": "Architecture (as implemented)",
         "nodes": [
             {"id": "fe", "label": "Frontend", "x": 0.7, "y": 2.4, "w": 2.6, "h": 1.0, "kind": "rounded"},
             {"id": "api", "label": "API layer", "x": 5.2, "y": 2.4, "w": 2.6, "h": 1.0, "kind": "rect"},
             {"id": "db", "label": "Database", "x": 9.8, "y": 2.4, "w": 2.4, "h": 1.0, "kind": "cylinder"},
         ],
         "edges": [
             {"from": "fe", "to": "api", "label": "HTTP"},
             {"from": "api", "to": "db", "label": "SQL"},
             {"from": "fe", "to": "db", "label": "backup", "dashed": True},
         ],
         "badge": "IMPLEMENTED (verified)", "notes": "Notes on diagram."},
        {"type": "image", "title": "Screenshot", "image": os.path.join(OUT_DIR, "tiny.png"),
         "caption": "Tiny synthetic PNG", "badge": "VERIFIED SCREENSHOT", "notes": "Notes on image."},
    ],
}


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(os.path.join(OUT_DIR, "tiny.png"), "wb") as f:
        f.write(TINY_PNG)
    theme = load_json(os.path.join(ROOT, "templates", "academic_theme.json"))
    out = os.path.join(OUT_DIR, "test_deck.pptx")
    build_deck(SPEC, theme, out)
    print(f"[1] build_deck: OK -> {out}")

    prs = Presentation(out)  # opens successfully = valid PPTX
    n = len(SPEC["slides"])
    assert len(prs.slides) == n, f"expected {n} slides, got {len(prs.slides)}"
    print(f"[2] file opens; slide count = {len(prs.slides)} (expected {n}): OK")

    from pptx.enum.shapes import MSO_SHAPE_TYPE
    texts = []
    tables = 0
    autoshapes = 0
    connectors = 0
    pictures = 0
    notes_with_text = 0
    for slide in prs.slides:
        if slide.has_notes_slide and slide.notes_slide.notes_text_frame.text.strip():
            notes_with_text += 1
        for shp in slide.shapes:
            if shp.has_text_frame:
                texts.append(shp.text_frame.text)
            if shp.shape_type == MSO_SHAPE_TYPE.AUTO_SHAPE:
                autoshapes += 1
            elif shp.shape_type == MSO_SHAPE_TYPE.LINE:
                connectors += 1
            elif shp.shape_type == MSO_SHAPE_TYPE.PICTURE:
                pictures += 1
            elif getattr(shp, "has_table", False) and shp.has_table:
                tables += 1
                assert len(shp.table.rows) == 3 and len(shp.table.columns) == 2
                for r in shp.table.rows:
                    for cell in r.cells:
                        texts.append(cell.text)
    flat = "\n".join(texts)
    assert "Bullets Slide" in flat and "First verified point" in flat, "editable text missing"
    assert "Tech Stack" in flat and "React" in flat, "table content missing"
    assert tables >= 1, "no editable table found"
    assert autoshapes >= 3 + 2 + 1, f"native shapes missing ({autoshapes})"  # diagram nodes + section band + badge
    assert connectors >= 3, f"connectors missing ({connectors})"
    assert pictures >= 1, "picture missing"
    assert notes_with_text >= 6, f"speaker notes missing (found on {notes_with_text} slides)"
    print(f"[3] editable text frames: OK; tables: {tables}; native shapes: {autoshapes}; "
          f"connectors: {connectors}; pictures: {pictures}")
    print(f"[4] speaker notes present on {notes_with_text}/{n} slides: OK")
    print("ALL ENGINE TESTS PASS")
    return 0


if __name__ == "__main__":
    sys.exit(main())
